#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

SConscript("baked_visibility/SCsub")
SConscript("dummy/SCsub")
SConscript("renderer_rd/SCsub")
SConscript("path_tracing/SCsub")
SConscript("storage/SCsub")
