#!/usr/bin/env bash
# Source-level gate for the optional Flux Metal ray-tracing and MetalFX path.
# It intentionally makes no Windows/Vulkan or runtime-performance claim.
set -euo pipefail

root="$(cd "$(dirname "$0")/../../.." && pwd)"
flux_h="$root/servers/rendering/renderer_rd/flux/render_flux.h"
flux_cpp="$root/servers/rendering/renderer_rd/flux/render_flux.cpp"
flux_shader="$root/servers/rendering/renderer_rd/flux/shaders/scene_flux.glsl"
flux_shader_inc="$root/servers/rendering/renderer_rd/flux/shaders/scene_flux_inc.glsl"
flux_shader_gen="$root/servers/rendering/renderer_rd/flux/shaders/scene_flux.glsl.gen.h"
effect_h="$root/servers/rendering/renderer_rd/flux/metal_flux_effect.h"
effect_cpp="$root/servers/rendering/renderer_rd/flux/metal_flux_effect.cpp"
forward_cpp="$root/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp"
forward_shader_inc="$root/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered_inc.glsl"
forward_shader_gen="$root/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl.gen.h"
compositor_cpp="$root/servers/rendering/renderer_rd/renderer_compositor_rd.cpp"
sky_cpp="$root/servers/rendering/renderer_rd/environment/sky.cpp"
editor_3d_cpp="$root/editor/scene/3d/node_3d_editor_plugin.cpp"
viewport_cpp="$root/servers/rendering/renderer_viewport.cpp"

require() {
	local pattern="$1" file="$2"
	if ! rg -Fq -- "$pattern" "$file"; then
		echo "missing Flux runtime wiring: $pattern ($file)" >&2
		exit 1
	fi
}

reject() {
	local pattern="$1" file="$2"
	if rg -Fq -- "$pattern" "$file"; then
		echo "obsolete Forward+ Flux wiring: $pattern ($file)" >&2
		exit 1
	fi
}

require "class RenderFlux" "$flux_h"
require "MetalFluxEffect" "$flux_h"
require "_process_metal_flux" "$flux_h"
require "MetalFluxEffect::render" "$effect_cpp"
require "bool has_tangents = false;" "$effect_h"
require "uint has_tangents;" "$effect_cpp"
require "offsetof(MetalFluxGeometry, has_tangents) == 76" "$effect_cpp"
require "surface.has_tangents = format & RSE::ARRAY_FORMAT_TANGENT" "$flux_cpp"
require "decode_oct_tangent" "$effect_cpp"
require "axis_angle_to_tbn" "$effect_cpp"
require "intersection_authored_tangent_basis" "$effect_cpp"
require "intersection_uv_derivative_tangent_basis" "$effect_cpp"
require "binormal * tangent_normal.y" "$effect_cpp"
require "SUPPORTS_RAYTRACING_PIPELINE" "$compositor_cpp"
require "RenderFlux" "$compositor_cpp"
require "rendering/flux/ray_tracing/enabled" "$flux_cpp"
require "rendering/flux/ray_tracing/geometry_lod/near_field_distance" "$flux_cpp"
require "PrimarySurfaceV1 material/visibility + Metal ray-owned direct shadows/GI/reflections" "$flux_cpp"
require "MetalFluxEffect" "$flux_cpp"
require "_process_metal_flux" "$flux_cpp"
require "guide_normal" "$effect_h"
require "guide_diffuse" "$effect_h"
require "guide_specular" "$effect_h"
require "guide_roughness" "$effect_h"
require "use_metalfx_denoiser" "$effect_h"
require "uint32_t hybrid_identity_low;" "$flux_h"
require "uint32_t hybrid_identity_high;" "$flux_h"
require "uint32_t hybrid_identity_padding_0;" "$flux_h"
require "uint32_t hybrid_identity_padding_1;" "$flux_h"
require "uint hybrid_identity_low;" "$flux_shader_inc"
require "uint hybrid_identity_high;" "$flux_shader_inc"
require "uint hybrid_identity_padding_0;" "$flux_shader_inc"
require "uint hybrid_identity_padding_1;" "$flux_shader_inc"
require "instances.data[instance_index].hybrid_identity_low" "$flux_shader"
require "MODE_FLUX_PRIMARY_SURFACE" "$flux_shader"
require "frag_color = vec4(emission, clamp(ao, 0.0, 1.0));" "$flux_shader"
require '"\n#define MODE_FLUX_PRIMARY_SURFACE\n#define SHADOWS_DISABLED\n"' "$root/servers/rendering/renderer_rd/flux/scene_shader_flux.cpp"
require "const int raster_shadow_count = p_render_raster_shadows ? p_render_data->render_shadow_count : 0;" "$flux_cpp"
require "hybrid_mode != 1, normal_roughness_views" "$flux_cpp"
require "primary_surface_geometry_output_buffer" "$flux_shader"
require "primary_surface_flags_output_buffer" "$flux_shader"
require "RB_TEX_PRIMARY_SURFACE_GEOMETRY" "$flux_h"
require "RB_TEX_PRIMARY_SURFACE_FLAGS" "$flux_h"
require "get_primary_surface_geometry_format" "$flux_cpp"
require "RD::DATA_FORMAT_R16G16B16A16_SFLOAT" "$flux_cpp"
require "RD::DATA_FORMAT_R32_UINT" "$flux_cpp"
require "hybrid_mode == 1 ? RID() : radiance_texture" "$flux_cpp"
require "PIPELINE_COLOR_PASS_FLAG_PRIMARY_SURFACE" "$flux_cpp"
require "_render_list_template<PASS_MODE_DEPTH_NORMAL_ROUGHNESS_HYBRID_MATERIAL>" "$flux_cpp"
require "primary_surface_version = 1" "$flux_cpp"
require "ray_owned_shading" "$flux_cpp"
require "transport_complete" "$flux_cpp"
require "primary_geometry_texture" "$effect_cpp"
require "primary_flags_texture" "$effect_cpp"
require "parameters.raster_primary_surface != 0u" "$effect_cpp"
require "const bool primary_valid" "$effect_cpp"
require "const bool have_punctual = parameters.punctual_light_count > 0u;" "$effect_cpp"
require "const float3 analytic_direct = have_punctual ? sample_punctual_lighting" "$effect_cpp"
require "primary_emission + emissive_direct + bidirectional_caustic_direct + analytic_direct" "$effect_cpp"
reject "Flux raster direct/shadows" "$flux_cpp"
require "TYPE_DIRECTIONAL" "$effect_h"
require "primary_analytic_contributed" "$effect_cpp"
require "collect_stage_probe" "$effect_h"
require "--flux-stage-probe-energy-scale=" "$flux_cpp"
require "stage_raw_analytic" "$effect_cpp"
require "stage_composite_output" "$effect_cpp"
require "const float3 filtered_diffuse = split_spatial_filter" "$effect_cpp"
require "const float3 filtered_specular = split_spatial_filter" "$effect_cpp"
require "ggx_direct_response(view_direction, world_normal, sample.direction" "$effect_cpp"
require "indirect * primary_ambient_occlusion" "$effect_cpp"
require "depth_texture.read(pixel) > 0.0f" "$effect_cpp"
require "invalid_pdf_samples" "$effect_cpp"
reject "const bool have_punctual = false;" "$effect_cpp"
reject "const float3 emissive_direct = 0.0f;" "$effect_cpp"
reject "min((reservoir.weight_sum + weight) * cap_scale, 1000000.0f)" "$effect_cpp"
reject "(environment_direct + indirect) * primary_ambient_occlusion" "$effect_cpp"
reject "_process_metal_flux(p_render_data, rb_data, true)" "$flux_cpp"
require "layout(set = 1, binding = 37) uniform texture2DArray flux_lighting_buffer;" "$flux_shader_inc"
require "uint hybrid_identity_low;" "$flux_shader_gen"
require "uint hybrid_identity_padding_1;" "$flux_shader_gen"
require "layout(set = 1, binding = 37) uniform texture2DArray flux_lighting_buffer;" "$flux_shader_gen"
require 'rendering_method == "forward_plus" || rendering_method == "flux"' "$viewport_cpp"
require "if (!high_end_renderer)" "$viewport_cpp"
require "VIEWPORT_SCALING_3D_MODE_METALFX_TEMPORAL" "$viewport_cpp"
require 'rendering/flux/ray_tracing/environment_lighting/enabled' "$sky_cpp"

reject "MetalFluxEffect" "$forward_cpp"
reject "metal_flux" "$forward_cpp"
reject "rendering/flux/ray_tracing" "$forward_cpp"
reject "reflection_guide_normal = hit_normal;" "$effect_cpp"
reject "hybrid_identity" "$forward_shader_inc"
reject "binding = 37" "$forward_shader_inc"
reject "hybrid_identity" "$forward_shader_gen"
reject "binding = 37" "$forward_shader_gen"
reject 'rendering/hybrid_renderer/environment_lighting/enabled' "$sky_cpp"
require "Flux ray tracing is session-only. Reset the UI and every editor viewport" "$editor_3d_cpp"
reject 'pd["hybrid_preview_enabled_v2"]' "$editor_3d_cpp"

echo "Flux Metal source gate passed."
